- name: play1
  hosts: web_servers
  gather_facts: false
  tasks:

    - name: update ec2 machine
      apt:
        update_cache: true

    - name: install latest nginx
      apt:
        name: nginx
        state: latest

    - name: copy index file
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
    
    - name: restart nginx service
      service:
        name: nginx
        state: restarted