- name: play_with_loop
  hosts: web_servers
  gather_facts: false
  vars:
    packages:
      - nginx
      - curl
      - sudo
  vars_files: ./my_vars.yml
  tasks:
   
    - name: update ec2 machine
      tags: always
      apt:
        update_cache: true

    - name: install packages list
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    - name: install packages with different states from packages_obj
      apt:
        name: "{{ item.package_name }}"
        state: "{{ item.package_state }}"
      loop: "{{ packages_obj }}"