- name: play1
  hosts: web_servers
  gather_facts: false
  tasks:
   
    #apt update
    - name: update ec2 machine
      tags: update
      apt:
        update_cache: true
   
    #apt install nginx
    - name: install latest nginx
      tags: install
      apt:
        name: nginx
        state: latest

    - name: copy index file
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
    
    - name: restart nginx service
      #sysvinit
      service:
        name: nginx
        state: restarted
    